version: "3"

volumes:
  node_modules:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - redis
    container_name: jump-jump-dev
    ports:
      - "8081:8081"
    environment:
      J2HttpPort: 8081
      J2RunMode: dev
      J2RedisAddr: redis:6379
    volumes:
      - "$PWD:/go/src/github.com/jwma/jump-jump"
    entrypoint: bee run

  frontend:
    build:
      context: ./admin-app
    container_name: jump-jump-admin-app-dev
    volumes:
      - "$PWD/admin-app:/home/node/app"
      - "node_modules:/home/node/app/node_modules"
    ports:
      - "8080:8080"
    working_dir: /home/node/app
    entrypoint: npm run serve

  redis:
    image: redis:latest
    volumes:
      - "$PWD/data/dev/redis:/data"
    ports:
      - "6380:6379"
    entrypoint: redis-server --appendonly yes
