version: "3"
services:
  web:
    build: .
    depends_on:
      - redis
    container_name: jump-jump-prod
    ports:
      - "8080:8080"
    environment:
      J2HttpPort: 8080
      J2RunMode: prod
      J2RedisAddr: redis:6379
    entrypoint: /go/src/github.com/jwma/jump-jump/app/app

  redis:
    image: redis:latest
    volumes:
      - "$PWD/data/prod/redis:/data"
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
